#joe https://learn.microsoft.com/en-us/training/modules/copilot-declarative-agent-action-api-plugin-vsc/1-introduction
#joe https://learn.microsoft.com/en-us/training/modules/copilot-declarative-agent-action-api-plugin-vsc/2-create-declarative-agent-api-plugin
#joe https://learn.microsoft.com/en-us/training/modules/copilot-declarative-agent-action-api-plugin-vsc/3-exercise-create-declarative-agent-api-plugin

openapi: 3.0.0



################################################
#joe add security https://learn.microsoft.com/en-us/training/modules/copilot-declarative-agent-api-plugin-auth/3-exercise-integrate-api-plugin-key
security:
  - bearerAuth: []
## hmm above is global .. the repairs project I not do puts it on each paths / not global
##It automatically applies to all your existing paths (/dishes and /orders).
##You do not need any per‑path security blocks.
################################################
###If you *did* have a `/repairs` endpoint, the structure would look like this:
###
###```yaml
##
###paths:
  ###/repairs:
    ###get:
      ###security:
        ###- bearerAuth: []
      ###summary: Example repairs endpoint
      ###responses:
        ###'200':
          ###description: OK
##
#######above is just a demonstration because your Il Ristorante API does not define /repairs, so you do not need this block unless you add that endpoint in the future.
################################################
########But you do **not** need to add this.
########Your global `security:` block already applies to ALL endpoints unless you override it.





info:
  title: Il Ristorante menu API--------JoeNote__url was http://localhost:7071/api  pre change https://learn.microsoft.com/en-us/training/modules/copilot-declarative-agent-action-api-plugin-vsc/3-exercise-create-declarative-agent-api-plugin
  version: 1.0.0
  description: API to retrieve dishes and place orders for Il Ristorante.
servers:
  - url: ${{OPENAPI_SERVER_URL}}/api
    description: Il Ristorante API servers url___was http://localhost:7071/api  which is the URL that Azure Functions uses when running locally.  See readme on how azure functions to imitate an api ---and see .vscode/tasks.json for start local tunnel task---------joenote
paths:
  /dishes:
    get:
      operationId: getDishes
      summary: Get all available dishes
      description: Retrieve a list of all dishes, optionally filtered by course and allergens.
      parameters:
        - in: query
          name: course
          schema:
            type: string
          description: Filter dishes by course. Can be breakfast, lunch, or dinner.
        - in: query
          name: name
          schema:
            type: string
          description: Find dishes by name.
        - in: query
          name: type
          schema:
            type: string
          description: Filter dishes by type. Can be dish or drink.
        - in: query
          name: allergens
          schema:
            type: array
            items:
              type: string
          description: Filter dishes to exclude specific allergens.
      responses:
        '200':
          description: A list of dishes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'

  /orders:
    post:
      operationId: placeOrder
      summary: Place an order
      description: Place an order by providing an array of dishes and quantities.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dishes:
                  type: array
                  description: List of items to order. Each item consists of a dish and a quantity.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the dish to order.
                      quantity:
                        type: integer
                        description: The quantity of the dish to order.
                    required:
                      - name
                      - quantity
              required:
                - dishes
      responses:
        '201':
          description: Order placed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: integer
                  status:
                    type: string
                    example: confirmed
                  total_price:
                    type: number
                    format: float
        '400':
          description: Invalid order request.




components:


################################################
#joe  Adding bearerAuth in OpenAPI does not enforce authentication.
#joe  It is metadata, not a gatekeeper.
#joe  
#joe  It tells the Copilot agent how to call a secure API
#joe  It does not modify your Il Ristorante Azure Function backend
#joe  It does not force authorization unless your Function code checks for it
#joe  
#joe  So your existing API endpoints (/dishes, /orders) will continue responding exactly as before.

  #joe add security https://learn.microsoft.com/en-us/training/modules/copilot-declarative-agent-api-plugin-auth/3-exercise-integrate-api-plugin-key
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
################################################



  schemas:
    Dish:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the dish.
        name:
          type: string
          description: The name of the dish.
        description:
          type: string
          description: A short description of the dish.
        image_url:
          type: string
          description: URL to an image of the dish.
        price:
          type: number
          format: float
          description: The price of the dish.
        allergens:
          type: array
          items:
            type: string
          description: List of allergens in the dish, if any.
        type:
          type: string
          description: The type of dish. Can be either a dish or a drink.
        course:
          type: string
          description: The course to which the dish belongs. Can be breakfast, lunch, or dinner.

